# Generated by Django 3.2.9 on 2021-11-02 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Актеры')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Фильм', 'Фильм'), ('Мультфильм', 'Мультфильм'), ('Аниме', 'Аниме')], max_length=100, verbose_name='Категории')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Режиссеры')),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Фильм', 'Фильм'), ('Мультфильм', 'Мультфильм'), ('Аниме', 'Аниме')], max_length=100, verbose_name='Жанры')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, verbose_name='Рейтинг')),
                ('release_year', models.IntegerField(blank=True, verbose_name='Год выпуска')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(blank=True, upload_to='Poster/%Y/%m/%d/', verbose_name='Постер')),
                ('video', models.FileField(blank=True, upload_to='Video/%Y/%m/%d/', verbose_name='Видео')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Время измениния')),
                ('actors', models.ManyToManyField(blank=True, to='film.Actors', verbose_name='Актеры')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.categories', verbose_name='Категории')),
                ('directors', models.ManyToManyField(blank=True, to='film.Directors', verbose_name='Режиссер')),
                ('genres', models.ManyToManyField(to='film.Genres', verbose_name='Жанры')),
            ],
            options={
                'verbose_name': 'Видео',
                'ordering': ['creat_time', 'name'],
            },
        ),
    ]
