# Generated by Django 3.2.9 on 2022-04-01 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Актеры')),
            ],
            options={
                'verbose_name': 'Актер',
                'verbose_name_plural': 'Актеры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Режиссеры')),
            ],
            options={
                'verbose_name': 'Режиссер',
                'verbose_name_plural': 'Режиссеры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Жанры')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='genre_URL')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0, verbose_name='Рейтинг')),
                ('release_year', models.IntegerField(blank=True, verbose_name='Год выпуска')),
                ('country', models.CharField(max_length=200, verbose_name='Страна')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('original_name', models.CharField(max_length=200, verbose_name='Оригинальное название')),
                ('image', models.ImageField(blank=True, upload_to='Poster', verbose_name='Постер')),
                ('video', models.FileField(blank=True, upload_to='Video', verbose_name='Видео')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='video_URL')),
                ('actors', models.ManyToManyField(blank=True, to='film.Actors', verbose_name='Актеры')),
                ('directors', models.ManyToManyField(blank=True, to='film.Directors', verbose_name='Режиссер')),
                ('genres', models.ManyToManyField(to='film.Genres', verbose_name='Жанры')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
                'ordering': ['creat_time', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserIpAndRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_rating_value', models.FloatField(default=1, verbose_name='Оценка пользователя')),
                ('ip', models.CharField(default='127.0.0.1', max_length=15, verbose_name='IP пользователя')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip', to='film.video', verbose_name='Видео id')),
            ],
            options={
                'verbose_name': 'IP и оценка каждого пользователя',
                'verbose_name_plural': 'IP и оценки каждого пользователя',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='User_pictures', verbose_name='Фото профиля')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=300, verbose_name='Комментарий')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Последние изменение')),
                ('active', models.BooleanField(default=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Имя')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='film.video', verbose_name='Последние изменение')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ('-created',),
            },
        ),
    ]
