# Generated by Django 3.2.9 on 2021-11-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_auto_20211103_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(blank=True, upload_to='Poser/<django.db.models.fields.CharField>', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, upload_to='Video/<django.db.models.fields.CharField>', verbose_name='Видео'),
        ),
    ]
