# Generated by Django 3.2.9 on 2021-11-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0005_auto_20211114_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='genres',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='genre_URL'),
        ),
    ]
