# Generated by Django 3.2.9 on 2022-01-09 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0006_genres_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='video',
            name='genres',
        ),
        migrations.AddField(
            model_name='video',
            name='Актеры',
            field=models.ManyToManyField(blank=True, to='film.Actors', verbose_name='Актеры'),
        ),
        migrations.AddField(
            model_name='video',
            name='Жанры',
            field=models.ManyToManyField(to='film.Genres', verbose_name='Жанры'),
        ),
    ]
