# Generated by Django 3.2.9 on 2022-01-09 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0007_auto_20220109_0446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='Актеры',
            new_name='actors',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='Жанры',
            new_name='genres',
        ),
    ]
