# Generated by Django 3.2.9 on 2022-01-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0012_auto_20220116_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='static/film/images/noavatar.png', upload_to='User_pictures', verbose_name='Фото профиля'),
        ),
    ]
