# Generated by Django 3.2.9 on 2022-01-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0014_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='User_pictures/noavatar.png', upload_to='User_pictures', verbose_name='Фото профиля'),
        ),
    ]
